### ISSUE TITLE
feature request:  sync notes with email on imap

### ISSUE THREAD

**Issue by luison** [mlazdans/qnote#41]
First, thank you for continuing support of this project.
I imagine it might be a difficult feature depending on the storage of the plugin but I've always thought that the missing feature of a noting system for imap is sharing the notes.
In our case we use imap as certain mailboxes are shared among various users. It would be great that this get synced between them on certain mailboxes or folders, which I imagine would require that the note is saved via imap on the email itself.
Thanks.

**Comment by mlazdans** [comment]
Duplicate #31

This would introduce unnecessary complexity. It's not trivial storing notes in message it self. Instead you could use some shared folder (Dropbox, Samba, etc) pretty easily.

**Comment by tylla** [comment]
If I may comment on this coming so late to the party, firstly it is not necessarily a duplicate as #31 suggests storing the notes in a designated IMAP folder, while this issue is about generally using IMAP to sync.

As about this issue, the perfect solution would be to store the note in the message header. It could be saved as a custom header entry which would get synced through IMAP to any other client and then retrieved and shown to the user.
One other extension that does something really similar is the [Edit Email Subject (EES)](https://addons.thunderbird.net/en-GB/thunderbird/addon/edit-email-subject/) which I think could be used as an example.
