### ISSUE TITLE
Option save on close

### ISSUE THREAD

**Issue by mlazdans** [mlazdans/qnote#69]
Add option to save note when press close button (red cross)

**Comment by bogdandragomir** [comment]
Yes, this would be very useful because in previous versions it was never necessary to save a note, they were saved automatically.
People are used to not saving, that's why they will lose notes.

I think people usually attach notes to emails to keep them for a long time, not just until they hit the close button. That's why autosave is useful.

Actually the close button is more confusing, it was better in previous versions, when you couldn't see the note of an email regarding another email.

**Comment by bogdandragomir** [comment]
And notes should be saved immediately, either implicitly or through a special option you can add, not just when you click the close note button (red cross). Because you can close Thunderbird and lose the note if you don't explicitly save it or close it, which wasn't necessary until a few weeks ago and people are used to not doing these operations.

**Comment by UrgulPL** [comment]
Please revert back to autosave notes, as it was in previous versions. At the moment using this extension is very problematic. There is not even a warning that the note will not be saved if you close the note or click another email.

**Comment by skaleta** [comment]
Yes, I also want the notes to be saved automatically when the window is closed (with the cross key, the Esc key...)

**Comment by mlazdans** [comment]
This option will be added in next release and enabled by default. Revert back to how it was originally.
