### ISSUE TITLE
QNote Keeps Disapperaing

### ISSUE THREAD

**Issue by Private61** [mlazdans/qnote#70]
Hi,
I'm running Thunderbird v115.16.3 (64-bit) on Windows 7 (yes I know).
QNote keeps disappearing. I add it, check the settings and the old notes as there too.
I close and then at a ramson numbe rof re-starts the Add-On disappears and I need to re-add it.
Does anyone know what is going on?

**Comment by mlazdans** [comment]
I will NOT support TB115, sorry. This version was an abomination 😅

**Comment by DenB10** [comment]
TB115 may be an abomination, but it's the last possible version for Windows 7!!!

I sympathize with Private61 because I'm also still on Windows 7 but I don't have the same problem. I can give him two suggestions:
1. Uninstall then reinstall QNote 0.13, taking care to make a backup of settings and notes beforehand.
2. If the problem persists, install QNote 0.13 with a blank Thunderbird profile to see if it conflicts with another extension (save your old profile first).
